"""new changes

Revision ID: 0065c5e90d26
Revises: 870083310462
Create Date: 2022-11-01 11:34:00.664149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0065c5e90d26'
down_revision = '870083310462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('lang', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'lang')
    # ### end Alembic commands ###
