"""new changes

Revision ID: 0b2e035c6960
Revises: c7860f106cfd
Create Date: 2023-01-23 18:09:16.514691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2e035c6960'
down_revision = 'c7860f106cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
