"""new changes

Revision ID: 3c66e8c07bca
Revises: 46774e8810d4
Create Date: 2023-01-30 17:55:42.396254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c66e8c07bca'
down_revision = '46774e8810d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
