"""new changes

Revision ID: 46774e8810d4
Revises: 0b2e035c6960
Create Date: 2023-01-29 17:24:40.670262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46774e8810d4'
down_revision = '0b2e035c6960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
