"""new changes

Revision ID: 4c60413b691c
Revises: 21c667b05c4e
Create Date: 2022-08-26 12:10:48.070826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c60413b691c'
down_revision = '21c667b05c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_course_survey', sa.Column('featured', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dynamic_course_survey', 'featured')
    # ### end Alembic commands ###
