"""new changes

Revision ID: 529de3c9dac5
Revises: 74fec387a58f
Create Date: 2022-11-09 13:43:43.518800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529de3c9dac5'
down_revision = '74fec387a58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
