"""new changes

Revision ID: 5f3d2fd0eec9
Revises: e4fcd3a2a15d
Create Date: 2022-11-09 14:05:50.910065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3d2fd0eec9'
down_revision = 'e4fcd3a2a15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course_tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_tags', type_='unique')
    # ### end Alembic commands ###
