"""new changes

Revision ID: 64299fbf5432
Revises: 81c51b001bca
Create Date: 2022-12-06 18:14:18.718425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64299fbf5432'
down_revision = '81c51b001bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('global_knowledge_test_user_results_ibfk_2', 'global_knowledge_test_user_results', type_='foreignkey')
    op.create_foreign_key(None, 'global_knowledge_test_user_results', 'global_knowledge_test_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_knowledge_test_user_results', type_='foreignkey')
    op.create_foreign_key('global_knowledge_test_user_results_ibfk_2', 'global_knowledge_test_user_results', 'knowledge_test_questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
