"""new changes

Revision ID: 81c51b001bca
Revises: 6c6ac25348c1
Create Date: 2022-12-06 17:40:00.649229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c51b001bca'
down_revision = '6c6ac25348c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
