"""new changes

Revision ID: 93903315cfae
Revises: b76fb0a380e0
Create Date: 2022-12-03 12:32:05.648514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93903315cfae'
down_revision = 'b76fb0a380e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('knowledge_test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_test_id'], ['knowledge_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_test_user_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_test_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_test_id'], ['knowledge_test.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['knowledge_test_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_test_user_results')
    op.drop_table('knowledge_test_questions')
    op.drop_table('knowledge_test')
    # ### end Alembic commands ###
