"""new changes

Revision ID: a5ec4b03a6e4
Revises: 4c60413b691c
Create Date: 2022-09-08 16:52:45.029968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ec4b03a6e4'
down_revision = '4c60413b691c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_lessons', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('dynamic_lessons', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('dynamic_lessons', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('dynamic_lessons', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'dynamic_lessons', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_lessons', type_='foreignkey')
    op.drop_column('dynamic_lessons', 'end_date')
    op.drop_column('dynamic_lessons', 'start_date')
    op.drop_column('dynamic_lessons', 'user_id')
    op.drop_column('dynamic_lessons', 'completed')
    # ### end Alembic commands ###
