"""new changes

Revision ID: bbfa53823715
Revises: b727f9c20ddf
Create Date: 2023-02-04 14:23:55.791298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfa53823715'
down_revision = 'b727f9c20ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
