"""new changes

Revision ID: c7860f106cfd
Revises: 64299fbf5432
Create Date: 2023-01-23 18:07:46.500098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7860f106cfd'
down_revision = '64299fbf5432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer_check_rule', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'answer_check_rule')
    # ### end Alembic commands ###
