"""new changes

Revision ID: e2cc7a7ba63d
Revises: a5ec4b03a6e4
Create Date: 2022-09-20 14:57:27.492602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2cc7a7ba63d'
down_revision = 'a5ec4b03a6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lessons_attempts')
    op.drop_constraint('answers_ibfk_1', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dynamic_course_survey_answers_ibfk_1', 'dynamic_course_survey_answers', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_course_survey_answers', 'dynamic_course_survey_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dynamic_course_survey_questions_ibfk_1', 'dynamic_course_survey_questions', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_course_survey_questions', 'dynamic_course_survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dynamic_course_survey_user_results_ibfk_1', 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint('dynamic_course_survey_user_results_ibfk_3', 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint('dynamic_course_survey_user_results_ibfk_4', 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint('dynamic_course_survey_user_results_ibfk_2', 'dynamic_course_survey_user_results', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_course_survey_user_results', 'dynamic_course_survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dynamic_course_survey_user_results', 'dynamic_course_survey_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dynamic_course_survey_user_results', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dynamic_course_survey_user_results', 'dynamic_course_survey_answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('enrolled_courses_ibfk_1', 'enrolled_courses', type_='foreignkey')
    op.create_foreign_key(None, 'enrolled_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('enrolled_lessons_ibfk_1', 'enrolled_lessons', type_='foreignkey')
    op.drop_constraint('enrolled_lessons_ibfk_2', 'enrolled_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'enrolled_lessons', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrolled_lessons', 'enrolled_courses', ['enrolled_course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lessons_ibfk_1', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_ibfk_1', 'lessons', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'enrolled_lessons', type_='foreignkey')
    op.drop_constraint(None, 'enrolled_lessons', type_='foreignkey')
    op.create_foreign_key('enrolled_lessons_ibfk_2', 'enrolled_lessons', 'enrolled_courses', ['enrolled_course_id'], ['id'])
    op.create_foreign_key('enrolled_lessons_ibfk_1', 'enrolled_lessons', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'enrolled_courses', type_='foreignkey')
    op.create_foreign_key('enrolled_courses_ibfk_1', 'enrolled_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint(None, 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint(None, 'dynamic_course_survey_user_results', type_='foreignkey')
    op.drop_constraint(None, 'dynamic_course_survey_user_results', type_='foreignkey')
    op.create_foreign_key('dynamic_course_survey_user_results_ibfk_2', 'dynamic_course_survey_user_results', 'user', ['user_id'], ['id'])
    op.create_foreign_key('dynamic_course_survey_user_results_ibfk_4', 'dynamic_course_survey_user_results', 'dynamic_course_survey_answers', ['answer_id'], ['id'])
    op.create_foreign_key('dynamic_course_survey_user_results_ibfk_3', 'dynamic_course_survey_user_results', 'dynamic_course_survey_questions', ['question_id'], ['id'])
    op.create_foreign_key('dynamic_course_survey_user_results_ibfk_1', 'dynamic_course_survey_user_results', 'dynamic_course_survey', ['survey_id'], ['id'])
    op.drop_constraint(None, 'dynamic_course_survey_questions', type_='foreignkey')
    op.create_foreign_key('dynamic_course_survey_questions_ibfk_1', 'dynamic_course_survey_questions', 'dynamic_course_survey', ['survey_id'], ['id'])
    op.drop_constraint(None, 'dynamic_course_survey_answers', type_='foreignkey')
    op.create_foreign_key('dynamic_course_survey_answers_ibfk_1', 'dynamic_course_survey_answers', 'dynamic_course_survey_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_ibfk_1', 'answers', 'lessons', ['lesson_id'], ['id'])
    op.create_table('lessons_attempts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='lessons_attempts_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='lessons_attempts_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('answers_history')
    # ### end Alembic commands ###
