"""new changes

Revision ID: e4fcd3a2a15d
Revises: 529de3c9dac5
Create Date: 2022-11-09 13:54:44.030927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4fcd3a2a15d'
down_revision = '529de3c9dac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tags', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('course_tags', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tags', sa.Column('tag', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('course_tags', 'name')
    # ### end Alembic commands ###
