"""new changes

Revision ID: f4c44c3ccb1b
Revises: ca95e562523c
Create Date: 2022-08-11 15:35:32.947895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4c44c3ccb1b'
down_revision = 'ca95e562523c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons_taken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lesson', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_lesson'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('courses_taken', 'completed',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses_taken', 'completed',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table('lessons_taken')
    # ### end Alembic commands ###
